#!/usr/bin/env python


###################################################################################################
#                                 Custom configurations                                           #
###################################################################################################

# Library name
LIB_NAME = 'correlation'

# Source for current project
sources = ['correlation']

# DFE_PRJ 
DFE_PRJs = ['correlation']

# Platform 
platform = 'SIMULATION'

# Include other C projects
C_PRJs = []

# Flags
cflags = '-std=gnu99 -finstrument-functions -fopenmp -fPIC -W -Wall'
ldflags = '-fopenmp'

# Macros for compiling
MACROS = '-Dparam_numTimesteps=param_numSteps -Dparam_numTimeseries=param_numVariables -Dinstream_in_data_pairs=instream_in_variable_pair -Dcorrelation_maxNumTimeseries=correlation_maxNumVariables'


###################################################################################################
#                                         Targets                                                 #
###################################################################################################

import os
from fabricate import *

prj_root = os.path.dirname(os.path.dirname(os.path.dirname(os.getcwd()))) + '/' 
setup(dirs=['.', prj_root])

def build():
	compile()
	link()	


def compile(build_dir='build', flags=cflags):

	# Include SLiC headers
	flags = flags + ' ' + shell("slic-config", "--cflags").strip().replace('\'', '')
	
	# Compile .max files into .o files
	for dfe in DFE_PRJs:
		max_dir = os.path.join(prj_root, "PLATFORMS", platform, "Maxfiles", dfe)	
		sapi_dir = os.path.join(prj_root,"PLATFORMS",platform,"SAPI", dfe)
		for maxfile in os.listdir(max_dir):
			if maxfile.endswith(".max"):	
				max_abs = os.path.join(max_dir, os.path.basename(maxfile))
				slic_abs = os.path.join(sapi_dir,os.path.splitext(maxfile)[0] + ".o")
				if os.path.isfile(max_abs):
					run ('sliccompile',  max_abs, slic_abs)  


	# Include all SAPI directories
	inc_sapi = ['-I' + os.path.join(prj_root, "PLATFORMS", platform, "SAPI", dfe) for dfe in DFE_PRJs]

	# Include C projects directories
	inc_c = ['-I' + os.path.join(prj_root, "PLATFORMS", platform, "MAPI", c_prj) for c_prj in C_PRJs]
	
	# Create buld directory
	run ('mkdir', build_dir)
	
	# Compile source code
	for source in sources:
		run ('gcc', '-c', os.path.join(source+'.c'), '-o', os.path.join(build_dir, source+'.o'), flags.split(), inc_sapi, inc_c, MACROS.split())
		

def link (build_dir='build', flags=ldflags):

	# Include SLiC libraries
	flags = flags + ' ' + shell("slic-config", "--libs").strip().replace('\'', '')

	# Object files
	objects = [os.path.join(build_dir, s+'.o') for s in sources]
	
	slic_objects = []
	for dfe in DFE_PRJs:
		sapi_dir = os.path.join(prj_root, "PLATFORMS", platform,"SAPI", dfe)
		for obj in os.listdir(sapi_dir):
			if obj.endswith(".o"):
				slic_abs = os.path.join(sapi_dir, os.path.basename(obj))
				slic_objects.append(slic_abs)

	mapi_libs = []
	for c_prj in C_PRJs:
		c_dir = os.path.join(prj_root, "PLATFORMS", platform, "MAPI", c_prj)
		for obj in os.listdir(c_dir):
			if obj.endswith(".a"):
				c_abs = os.path.join(c_dir, os.path.basename(obj))
				mapi_libs.append(c_abs)

	# Make static library 
	run ('ar', 'rcs', os.path.join(build_dir,LIB_NAME)+'.a', objects, slic_objects, mapi_libs)	
	
	# Making new directory for this project and copying executable
	mapi_dir = os.path.join(prj_root, "PLATFORMS", platform, 'MAPI', os.path.basename(os.getcwd()))
	run ('mkdir', mapi_dir)
	run ('cp', os.path.join(build_dir,LIB_NAME+'.a'), mapi_dir)

def clean():
	autoclean()

main ()
